# Myhistory/.streamlit/config.toml

[server]
enableStaticServing = true
folderUpload = false
maxUploadSize = 1000
maxMessageSize = 1000 # MB, 必要ならサイズを調整

[browser]
gatherUsageStats = false

[server.static]
folder = "static"